# Generated by Django 5.2.9 on 2026-01-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0002_add_athens_tenant_id'),
        ('quality', '0002_remove_qualityinspection_project_id_and_more'),
    ]

    operations = [
    ]
