# Generated by Django 5.2.9 on 2026-01-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_merge_20260103_1152'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='qualitydefect',
            name='quality_defect_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualityinspection',
            name='quality_inspection_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualityinspection',
            name='quality_inspection_tenant_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualitytemplate',
            name='quality_template_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierquality',
            name='quality_supplier_tenant_idx',
        ),
        migrations.RemoveField(
            model_name='qualityalert',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='qualitydefect',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='qualityinspection',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='qualitymetrics',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='qualitystandard',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='qualitytemplate',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='supplierquality',
            name='athens_tenant_id',
        ),
    ]
