# Generated by Django 5.2.9 on 2026-01-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0003_merge_20260103_1152'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inspection',
            name='inspection_inspection_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='inspection',
            name='inspection_inspection_tenant_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='inspectionitem',
            name='inspection_item_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='inspectionreport',
            name='inspection_report_tenant_idx',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='inspectionitem',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='inspectionreport',
            name='athens_tenant_id',
        ),
    ]
