# Generated by Codex on 2026-01-05

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ('athens_tenant_id', models.UUIDField(blank=True, null=True)),
                ('module', models.CharField(choices=[('REGULAR', 'Regular'), ('TBT', 'Toolbox Talk'), ('TRAINING', 'Training'), ('MOM', 'MOM')], max_length=20)),
                ('module_ref_id', models.CharField(blank=True, max_length=64, null=True)),
                ('event_type', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out')], max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('client_event_id', models.CharField(max_length=100)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('offline', models.BooleanField(default=False)),
                ('location', models.JSONField(blank=True, null=True)),
                ('method', models.CharField(choices=[('FACE', 'Face'), ('QR', 'QR'), ('PIN', 'PIN'), ('SELF_CONFIRM', 'Self Confirm'), ('HOST', 'Host'), ('MANUAL', 'Manual')], max_length=20)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [
                    models.Index(fields=['athens_tenant_id', 'user', 'occurred_at'], name='attendance_event_user_time_idx'),
                    models.Index(fields=['athens_tenant_id', 'module', 'module_ref_id', 'occurred_at'], name='attendance_event_module_time_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('athens_tenant_id', 'client_event_id'), name='attendance_event_tenant_client_event_unique'),
                ],
            },
        ),
    ]
