from authentication.models import ProjectAdmin

# Fetch the existing masteradmin user by username
master_admin = ProjectAdmin.objects.get(username='masteradmin')

# Set the flags to False to indicate password is set and reset not required
master_admin.is_autogenerated_password = False
master_admin.is_password_reset_required = False

# Optionally, set a new password if needed
# master_admin.set_password('your_new_password_here')

master_admin.save()

