#!/usr/bin/env python
import os
import django
import sys
from datetime import date, timedelta
import random

# Setup Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()

from authentication.models import CustomUser, Project, UserDetail, CompanyDetail, AdminDetail

def create_demo_data():
    print("🚀 Creating comprehensive demo data...")
    
    # 1. Create Projects
    projects_data = [
        {
            'projectName': 'Solar Power Plant - Phase 1',
            'projectCategory': 'power_and_energy',
            'capacity': '500 MW',
            'location': 'Rajasthan, India',
            'latitude': 27.0238,
            'longitude': 74.2179,
            'nearestPoliceStation': 'Jodhpur Police Station',
            'nearestPoliceStationContact': '+91-291-2545454',
            'nearestHospital': 'AIIMS Jodhpur',
            'nearestHospitalContact': '+91-291-2740740',
            'commencementDate': date(2024, 1, 15),
            'deadlineDate': date(2025, 12, 31)
        },
        {
            'projectName': 'Wind Energy Farm - Gujarat',
            'projectCategory': 'power_and_energy',
            'capacity': '300 MW',
            'location': 'Kutch, Gujarat',
            'latitude': 23.7337,
            'longitude': 68.7333,
            'nearestPoliceStation': 'Bhuj Police Station',
            'nearestPoliceStationContact': '+91-2832-250100',
            'nearestHospital': 'GK General Hospital',
            'nearestHospitalContact': '+91-2832-250200',
            'commencementDate': date(2024, 3, 1),
            'deadlineDate': date(2026, 2, 28)
        },
        {
            'projectName': 'Manufacturing Plant - Tamil Nadu',
            'projectCategory': 'manufacturing',
            'capacity': '1000 Units/Day',
            'location': 'Chennai, Tamil Nadu',
            'latitude': 13.0827,
            'longitude': 80.2707,
            'nearestPoliceStation': 'Guindy Police Station',
            'nearestPoliceStationContact': '+91-44-22250500',
            'nearestHospital': 'Apollo Hospital',
            'nearestHospitalContact': '+91-44-28296000',
            'commencementDate': date(2024, 6, 1),
            'deadlineDate': date(2025, 8, 31)
        }
    ]
    
    projects = []
    for project_data in projects_data:
        project, created = Project.objects.get_or_create(
            projectName=project_data['projectName'],
            defaults=project_data
        )
        projects.append(project)
        if created:
            print(f"✅ Created project: {project.projectName}")
    
    # 2. Create Project Admins for each project
    admin_types = ['client', 'epc', 'contractor']
    companies = {
        'client': ['Green Energy Corp', 'Renewable Solutions Ltd', 'EcoTech Industries'],
        'epc': ['PowerTech Engineering', 'Energy Systems Pvt Ltd', 'Solar Dynamics'],
        'contractor': ['BuildRight Construction', 'MegaConstruct Ltd', 'Infrastructure Pro']
    }
    
    project_admins = []
    for i, project in enumerate(projects):
        for admin_type in admin_types:
            username = f"{admin_type}_admin_{project.id}"
            company_name = companies[admin_type][i % len(companies[admin_type])]
            
            admin, created = CustomUser.objects.get_or_create(
                username=username,
                defaults={
                    'email': f"{username}@{company_name.lower().replace(' ', '')}.com",
                    'user_type': 'projectadmin',
                    'admin_type': admin_type,
                    'project': project,
                    'company_name': company_name,
                    'registered_address': f"123 Business District, {project.location}",
                    'name': f"{admin_type.title()} Admin",
                    'surname': f"Project {project.id}",
                    'phone_number': f"+91-{random.randint(7000000000, 9999999999)}",
                    'is_password_reset_required': False,
                    'is_autogenerated_password': False,
                    'is_active': True
                }
            )
            admin.set_password('admin123')
            admin.save()
            project_admins.append(admin)
            
            if created:
                print(f"✅ Created {admin_type} admin: {username}")
    
    # 3. Create Admin Users for each Project Admin
    designations = ['Site Engineer', 'Safety Officer', 'Quality Manager', 'Project Coordinator', 'Technical Lead']
    departments = ['Engineering', 'Safety', 'Quality', 'Operations', 'Technical']
    
    admin_users = []
    for project_admin in project_admins:
        for i in range(3):  # 3 users per admin
            username = f"{project_admin.admin_type}user_{project_admin.project.id}_{i+1}"
            designation = designations[i % len(designations)]
            department = departments[i % len(departments)]
            
            user, created = CustomUser.objects.get_or_create(
                username=username,
                defaults={
                    'email': f"{username}@{project_admin.company_name.lower().replace(' ', '')}.com",
                    'user_type': 'adminuser',
                    'admin_type': f"{project_admin.admin_type}user",
                    'project': project_admin.project,
                    'company_name': project_admin.company_name,
                    'name': f"{designation.split()[0]}",
                    'surname': f"User {i+1}",
                    'designation': designation,
                    'department': department,
                    'grade': ['A', 'B', 'C'][i % 3],
                    'created_by': project_admin,
                    'is_password_reset_required': False,
                    'is_autogenerated_password': False,
                    'is_active': True
                }
            )
            user.set_password('user123')
            user.save()
            admin_users.append(user)
            
            if created:
                print(f"✅ Created admin user: {username}")
    
    # 4. Create UserDetails for admin users
    for user in admin_users:
        user_detail, created = UserDetail.objects.get_or_create(
            user=user,
            defaults={
                'employee_id': f"EMP{user.id:04d}",
                'gender': random.choice(['Male', 'Female']),
                'father_or_spouse_name': f"Father of {user.name}",
                'date_of_birth': date(1980 + random.randint(0, 25), random.randint(1, 12), random.randint(1, 28)),
                'nationality': 'Indian',
                'education_level': random.choice(['B.Tech', 'M.Tech', 'Diploma', 'B.Sc', 'M.Sc']),
                'date_of_joining': date(2023, random.randint(1, 12), random.randint(1, 28)),
                'mobile': f"+91-{random.randint(7000000000, 9999999999)}",
                'uan': f"UAN{random.randint(100000000000, 999999999999)}",
                'pan': f"ABCDE{random.randint(1000, 9999)}F",
                'aadhaar': f"{random.randint(100000000000, 999999999999)}",
                'mark_of_identification': 'Scar on left hand',
                'is_approved': True
            }
        )
        if created:
            print(f"✅ Created user detail for: {user.username}")
    
    # 5. Create AdminDetails for project admins
    for admin in project_admins:
        admin_detail, created = AdminDetail.objects.get_or_create(
            user=admin,
            defaults={
                'name': admin.name,
                'phone_number': admin.phone_number,
                'pan_number': f"ADMIN{random.randint(1000, 9999)}P",
                'gst_number': f"GST{random.randint(10000000000000, 99999999999999)}",
                'is_approved': True
            }
        )
        if created:
            print(f"✅ Created admin detail for: {admin.username}")
    
    # 6. Create Company Details for master admin
    master_admin = CustomUser.objects.filter(admin_type='master').first()
    if master_admin:
        company_detail, created = CompanyDetail.objects.get_or_create(
            user=master_admin,
            defaults={
                'company_name': 'Athens EHS Solutions Pvt Ltd',
                'registered_office_address': '123 Tech Park, Bangalore, Karnataka, India - 560001',
                'pan': 'ATHENS1234P',
                'gst': 'GST29ATHENS1234P1Z5',
                'contact_phone': '+91-80-12345678',
                'contact_email': 'info@athens-ehs.com',
                'project_capacity_completed': 25,
                'project_capacity_ongoing': 8
            }
        )
        if created:
            print(f"✅ Created company detail for master admin")
    
    print("\n🎉 Demo data creation completed!")
    print(f"📊 Summary:")
    print(f"   • Projects: {Project.objects.count()}")
    print(f"   • Total Users: {CustomUser.objects.count()}")
    print(f"   • Project Admins: {CustomUser.objects.filter(user_type='projectadmin').count()}")
    print(f"   • Admin Users: {CustomUser.objects.filter(user_type='adminuser').count()}")
    print(f"   • User Details: {UserDetail.objects.count()}")
    print(f"   • Admin Details: {AdminDetail.objects.count()}")
    print(f"   • Company Details: {CompanyDetail.objects.count()}")
    
    print("\n🔑 Login Credentials:")
    print("Master Admin: master / master@123")
    print("Project Admins: [admin_type]_admin_[project_id] / admin123")
    print("Admin Users: [admin_type]user_[project_id]_[number] / user123")
    print("\nExample: client_admin_1 / admin123")
    print("Example: clientuser_1_1 / user123")

if __name__ == '__main__':
    create_demo_data()