from django.core.management.base import BaseCommand
from authentication.models import CustomUser
from django.contrib.auth.models import Permission

class Command(BaseCommand):
    help = 'Creates a Master Admin user with the given username and password'

    def add_arguments(self, parser):
        parser.add_argument('username', type=str, help='Username for the Master Admin')
        parser.add_argument('password', type=str, help='Password for the Master Admin')
        parser.add_argument('--email', type=str, help='Email for the Master Admin (optional)')

    def handle(self, *args, **options):
        # Check if a Master Admin already exists
        if CustomUser.objects.filter(admin_type='master').exists():
            self.stdout.write(self.style.ERROR('A Master Admin already exists. Only one Master Admin is allowed.'))
            return

        username = options['username']
        password = options['password']
        email = options.get('email')

        # Check if user already exists
        if CustomUser.objects.filter(username=username).exists():
            self.stdout.write(self.style.ERROR(f'User with username {username} already exists'))
            return

        # Create the Master Admin user
        user = CustomUser(
            username=username,
            email=email or f"{username}@master.admin",  # Provide default email if not given
            user_type='projectadmin',
            admin_type='master',
            is_autogenerated_password=False,
            is_password_reset_required=False,
            is_active=True,
            is_staff=True,  # Give staff permissions for admin site access
            is_superuser=True,  # Give superuser permissions
            project=None,  # Master admin doesn't belong to a specific project
            company_name='Master Admin',  # Provide a default company name
        )
        user.set_password(password)
        user.save()
        
        # Add all permissions to the user
        all_permissions = Permission.objects.all()
        user.user_permissions.set(all_permissions)

        self.stdout.write(self.style.SUCCESS(f'Successfully created Master Admin user: {username}'))
