from django.core.management.base import BaseCommand, CommandError
from authentication.models import CustomUser
from authentication.password_utils import generate_secure_password, validate_password_strength


class Command(BaseCommand):
    help = 'Superadmin can reset master admin password and enable password reset capability'

    def add_arguments(self, parser):
        parser.add_argument('username', type=str, help='Username of the master admin')
        parser.add_argument('--password', type=str, help='New password (if not provided, a secure password will be generated)')
        parser.add_argument('--generate', action='store_true', help='Generate a secure password automatically')

    def handle(self, *args, **options):
        username = options['username']
        password = options.get('password')
        
        # Generate password if requested or not provided
        if options['generate'] or not password:
            password = generate_secure_password()
            generated = True
        else:
            generated = False
            # Validate provided password
            is_valid, message = validate_password_strength(password)
            if not is_valid:
                raise CommandError(f'Password validation failed: {message}')

        try:
            # Find master admin user
            master_admin = CustomUser.objects.get(
                username=username,
                admin_type='master'
            )
        except CustomUser.DoesNotExist:
            raise CommandError(f'Master admin user "{username}" not found')

        try:
            # Reset password and enable reset capability
            master_admin.set_password(password)
            master_admin.is_autogenerated_password = True  # Mark as system-generated
            master_admin.is_password_reset_required = True  # Require reset on next login
            master_admin.can_reset_password = True  # Enable password reset
            master_admin.password_set_by_superadmin = True  # Mark as superadmin-set
            master_admin.save()
            
            self.stdout.write(
                self.style.SUCCESS(
                    f'Successfully reset password for master admin "{username}". '
                    f'They can now reset it once.'
                )
            )
            
            if generated:
                self.stdout.write(
                    self.style.WARNING(f'Generated password: {password}')
                )
                self.stdout.write(
                    self.style.WARNING(
                        'Please provide this password to the master admin securely.'
                    )
                )
            
            self.stdout.write(
                self.style.WARNING(
                    'The master admin can reset this password once. After that, '
                    'only superadmin can provide a new password.'
                )
            )
            
        except Exception as e:
            raise CommandError(f'Error resetting password: {str(e)}')