# Generated by Django 5.2.5 on 2025-08-28 02:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color_code', models.CharField(default='#1890ff', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyManpowerSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_workers', models.PositiveIntegerField(default=0)),
                ('total_hours', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('total_overtime', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('half_day_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='authentication.project')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'project')},
            },
        ),
        migrations.CreateModel(
            name='ManpowerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('shift', models.CharField(blank=True, choices=[('day', 'Day Shift'), ('night', 'Night Shift'), ('general', 'General')], default='general', max_length=10, null=True)),
                ('hours_worked', models.DecimalField(blank=True, decimal_places=1, default=8.0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('overtime_hours', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('attendance_status', models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day')], default='present', max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_manpower_entries', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_entries', to='authentication.project')),
                ('work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manpower_entries', to='manpower.worktype')),
            ],
            options={
                'ordering': ['-date', 'category', 'gender'],
                'permissions': [('view_all_manpower', 'Can view all manpower entries'), ('manage_manpower', 'Can manage manpower entries')],
                'unique_together': {('date', 'category', 'gender', 'work_type', 'shift', 'created_by')},
            },
        ),
    ]
