# Generated by Django 5.2.9 on 2026-01-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manpower', '0002_add_athens_tenant_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailymanpowersummary',
            name='manpower_summary_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailymanpowersummary',
            name='manpower_summary_tenant_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='manpowerentry',
            name='manpower_entry_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='manpowerentry',
            name='manpower_entry_tenant_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='worktype',
            name='manpower_worktype_tenant_idx',
        ),
        migrations.RemoveField(
            model_name='dailymanpowersummary',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='manpowerentry',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='worktype',
            name='athens_tenant_id',
        ),
    ]
