# Generated by Django 6.0 on 2025-12-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentcostcenter',
            name='cost_type',
            field=models.CharField(choices=[('medical', 'Medical Treatment'), ('property_damage', 'Property Damage'), ('property_repair', 'Property Repair'), ('equipment_replacement', 'Equipment Replacement'), ('production_loss', 'Production Loss'), ('overtime', 'Overtime Costs'), ('contractor_fees', 'Contractor Fees'), ('legal_fees', 'Legal Fees'), ('regulatory_fine', 'Regulatory Fine'), ('environmental_cleanup', 'Environmental Cleanup'), ('investigation_costs', 'Investigation Costs'), ('training_costs', 'Training Costs'), ('other', 'Other')], max_length=50, verbose_name='Cost Type'),
        ),
    ]
