# Generated by Django 5.2.9 on 2026-01-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentmanagement', '0002_add_athens_tenant_id'),
        ('incidentmanagement', '0002_alter_incidentcostcenter_cost_type'),
    ]

    operations = [
    ]
