# Generated by Django 5.2.9 on 2026-01-04 04:45

from django.db import migrations, models, connection


class Migration(migrations.Migration):

    dependencies = [
        ('incidentmanagement', '0003_merge_20260103_1152'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[] if connection.vendor == 'sqlite' else [
                migrations.RunSQL("DROP INDEX IF EXISTS incident_8d_process_tenant_idx;"),
                migrations.RunSQL("DROP INDEX IF EXISTS incident_8d_process_tenant_status_idx;"),
                migrations.RunSQL("DROP INDEX IF EXISTS incident_incident_tenant_idx;"),
                migrations.RunSQL("DROP INDEX IF EXISTS incident_incident_tenant_status_idx;"),
                migrations.RunSQL("DROP INDEX IF EXISTS incident_incident_tenant_severity_idx;"),
                migrations.RunSQL(
                    "ALTER TABLE incidentmanagement_eightdanalysismethod "
                    "DROP COLUMN IF EXISTS athens_tenant_id;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE incidentmanagement_eightdcontainmentaction "
                    "DROP COLUMN IF EXISTS athens_tenant_id;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE incidentmanagement_eightdcorrectiveaction "
                    "DROP COLUMN IF EXISTS athens_tenant_id;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE incidentmanagement_eightddiscipline "
                    "DROP COLUMN IF EXISTS athens_tenant_id;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE incidentmanagement_eightdpreventionaction "
                    "DROP COLUMN IF EXISTS athens_tenant_id;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE incidentmanagement_eightdprocess "
                    "DROP COLUMN IF EXISTS athens_tenant_id;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE incidentmanagement_eightdrootcause "
                    "DROP COLUMN IF EXISTS athens_tenant_id;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE incidentmanagement_eightdteam "
                    "DROP COLUMN IF EXISTS athens_tenant_id;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE incidentmanagement_incidentattachment "
                    "DROP COLUMN IF EXISTS athens_tenant_id;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE incidentmanagement_incidentauditlog "
                    "DROP COLUMN IF EXISTS athens_tenant_id;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE incidentmanagement_incidentcategory "
                    "DROP COLUMN IF EXISTS athens_tenant_id;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE incidentmanagement_incidentcostcenter "
                    "DROP COLUMN IF EXISTS athens_tenant_id;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE incidentmanagement_incidentlearning "
                    "DROP COLUMN IF EXISTS athens_tenant_id;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE incidentmanagement_incidentmetrics "
                    "DROP COLUMN IF EXISTS athens_tenant_id;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE incidentmanagement_incidentnotification "
                    "DROP COLUMN IF EXISTS athens_tenant_id;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE incidentmanagement_incidentworkflow "
                    "DROP COLUMN IF EXISTS athens_tenant_id;"
                ),
                migrations.RunSQL(
                    "ALTER TABLE incidentmanagement_riskassessmenttemplate "
                    "DROP COLUMN IF EXISTS athens_tenant_id;"
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='eightdprocess',
                    name='incident_8d_process_tenant_idx',
                ),
                migrations.RemoveIndex(
                    model_name='eightdprocess',
                    name='incident_8d_process_tenant_status_idx',
                ),
                migrations.RemoveIndex(
                    model_name='incident',
                    name='incident_incident_tenant_idx',
                ),
                migrations.RemoveIndex(
                    model_name='incident',
                    name='incident_incident_tenant_status_idx',
                ),
                migrations.RemoveIndex(
                    model_name='incident',
                    name='incident_incident_tenant_severity_idx',
                ),
                migrations.RemoveField(
                    model_name='eightdanalysismethod',
                    name='athens_tenant_id',
                ),
                migrations.RemoveField(
                    model_name='eightdcontainmentaction',
                    name='athens_tenant_id',
                ),
                migrations.RemoveField(
                    model_name='eightdcorrectiveaction',
                    name='athens_tenant_id',
                ),
                migrations.RemoveField(
                    model_name='eightddiscipline',
                    name='athens_tenant_id',
                ),
                migrations.RemoveField(
                    model_name='eightdpreventionaction',
                    name='athens_tenant_id',
                ),
                migrations.RemoveField(
                    model_name='eightdprocess',
                    name='athens_tenant_id',
                ),
                migrations.RemoveField(
                    model_name='eightdrootcause',
                    name='athens_tenant_id',
                ),
                migrations.RemoveField(
                    model_name='eightdteam',
                    name='athens_tenant_id',
                ),
                migrations.RemoveField(
                    model_name='incidentattachment',
                    name='athens_tenant_id',
                ),
                migrations.RemoveField(
                    model_name='incidentauditlog',
                    name='athens_tenant_id',
                ),
                migrations.RemoveField(
                    model_name='incidentcategory',
                    name='athens_tenant_id',
                ),
                migrations.RemoveField(
                    model_name='incidentcostcenter',
                    name='athens_tenant_id',
                ),
                migrations.RemoveField(
                    model_name='incidentlearning',
                    name='athens_tenant_id',
                ),
                migrations.RemoveField(
                    model_name='incidentmetrics',
                    name='athens_tenant_id',
                ),
                migrations.RemoveField(
                    model_name='incidentnotification',
                    name='athens_tenant_id',
                ),
                migrations.RemoveField(
                    model_name='incidentworkflow',
                    name='athens_tenant_id',
                ),
                migrations.RemoveField(
                    model_name='riskassessmenttemplate',
                    name='athens_tenant_id',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='incident',
            name='athens_tenant_id',
            field=models.UUIDField(blank=True, help_text='Athens tenant identifier for multi-tenant isolation', null=True),
        ),
    ]
