# Generated by Django 5.2.9 on 2026-01-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0002_add_athens_tenant_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='permit',
            name='ptw_permit_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='permit',
            name='ptw_permit_tenant_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='permittype',
            name='ptw_permittype_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflowinstance',
            name='ptw_workflow_tenant_idx',
        ),
        migrations.RemoveField(
            model_name='compliancereport',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='digitalsignature',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='escalationrule',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='gasreading',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='hazardlibrary',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='permitapproval',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='permitaudit',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='permitextension',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='permithazard',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='permitphoto',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='permittype',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='permitworker',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='systemintegration',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='workflowinstance',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='workflowtemplate',
            name='athens_tenant_id',
        ),
    ]
