# Generated by Codex for permit type templates.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0010_canonicalize_permit_statuses'),
        ('authentication', '0013_project_menu_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='permittype',
            name='form_template',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='permittype',
            name='project_overrides_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permit',
            name='permit_parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PermitTypeTemplateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_template', models.JSONField(blank=True, default=dict)),
                ('override_prefill', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_overrides', to='ptw.permittype')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_type_template_overrides', to='authentication.project')),
            ],
            options={
                'unique_together': {('project', 'permit_type')},
            },
        ),
    ]
