# Generated by Django 5.1.4 on 2026-01-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0014_webhook_dedupe_per_webhook'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='isolationpointlibrary',
            new_name='ptw_isolati_project_348eb9_idx',
            old_name='ptw_isolati_project_idx',
        ),
        migrations.RenameIndex(
            model_name='isolationpointlibrary',
            new_name='ptw_isolati_project_8d0b90_idx',
            old_name='ptw_isolati_project_asset_idx',
        ),
        migrations.RenameIndex(
            model_name='isolationpointlibrary',
            new_name='ptw_isolati_project_174cd3_idx',
            old_name='ptw_isolati_project_site_idx',
        ),
        migrations.RenameIndex(
            model_name='permitisolationpoint',
            new_name='ptw_permiti_permit__4bd7f2_idx',
            old_name='ptw_permiti_permit_status_idx',
        ),
        migrations.RenameIndex(
            model_name='permitisolationpoint',
            new_name='ptw_permiti_point_i_9585fe_idx',
            old_name='ptw_permiti_point_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdeliverylog',
            new_name='ptw_webhook_webhook_b4b88b_idx',
            old_name='ptw_webhook_delivery_webhook_event_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdeliverylog',
            new_name='ptw_webhook_permit__9dab8e_idx',
            old_name='ptw_webhook_delivery_permit_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdeliverylog',
            new_name='ptw_webhook_sent_at_4bfa35_idx',
            old_name='ptw_webhook_delivery_sent_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookendpoint',
            new_name='ptw_webhook_project_b3e2f5_idx',
            old_name='ptw_webhook_project_enabled_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookendpoint',
            new_name='ptw_webhook_enabled_b8f097_idx',
            old_name='ptw_webhook_enabled_idx',
        ),
        migrations.AddField(
            model_name='permit',
            name='other_hazards',
            field=models.TextField(blank=True, default='', help_text='Additional hazards not covered in standard categories'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
    ]
