# Generated by Django 5.1.4 on 2026-01-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0016_alter_permit_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalsignature',
            name='payload_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='digitalsignature',
            name='signature_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permitaudit',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('extended', 'Extended'), ('modified', 'Modified'), ('viewed', 'Viewed'), ('printed', 'Printed'), ('exported', 'Exported')], max_length=20),
        ),
    ]
