# Generated by Codex for PTW status canonicalization.

from django.db import migrations


LEGACY_STATUS_MAP = {
    'pending_verification': 'submitted',
    'verified': 'under_review',
    'pending_approval': 'under_review',
    'in_progress': 'active',
    'closed': 'completed',
}

CANONICAL_STATUSES = {
    'draft',
    'submitted',
    'under_review',
    'approved',
    'active',
    'suspended',
    'completed',
    'cancelled',
    'expired',
    'rejected',
}


def forwards(apps, schema_editor):
    Permit = apps.get_model('ptw', 'Permit')
    WorkflowStep = apps.get_model('ptw', 'WorkflowStep')

    for legacy, canonical in LEGACY_STATUS_MAP.items():
        Permit.objects.filter(status=legacy).update(status=canonical)

    Permit.objects.exclude(status__in=CANONICAL_STATUSES).update(status='submitted')
    WorkflowStep.objects.filter(status='obsolete').update(status='skipped')


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0009_add_version_and_idempotency'),
        ('ptw', '0011_webhooks'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
