# Generated by Django 5.2.5 on 2025-08-28 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='progress',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='backupFrequency',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='defaultUserRole',
            field=models.CharField(choices=[('clientuser', 'Client User'), ('epcuser', 'EPC User'), ('contractoruser', 'Contractor User')], default='clientuser', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='logLevel',
            field=models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='maxFileSize',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='sessionTimeout',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)]),
        ),
    ]
