# Generated by Django 5.2.9 on 2026-01-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safetyobservation', '0004_merge_20260103_1152'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='safetyobservation',
            name='safety_obs_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='safetyobservation',
            name='safety_obs_tenant_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='safetyobservationfile',
            name='safety_obs_file_tenant_idx',
        ),
        migrations.RemoveField(
            model_name='safetyobservation',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='safetyobservationfile',
            name='athens_tenant_id',
        ),
    ]
