# Generated by Django 5.2.5 on 2025-08-28 02:42

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=64)),
                ('record_id', models.IntegerField(db_index=True)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('chunk', models.TextField()),
                ('embedding', pgvector.django.VectorField(dimensions=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['module', 'record_id'], name='ai_bot_doce_module_2806bc_idx')],
                'unique_together': {('module', 'record_id', 'chunk')},
            },
        ),
    ]
