# Generated by Django 5.2.9 on 2026-01-16 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptw', '0012_add_permit_type_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitToolboxTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('conducted_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='permit_toolbox_talks/')),
                ('url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toolbox_talks_conducted', to=settings.AUTH_USER_MODEL)),
                ('permit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_talk', to='ptw.permit')),
            ],
        ),
        migrations.CreateModel(
            name='PermitToolboxTalkAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('ack_signature', models.TextField(blank=True)),
                ('permit_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tbt_attendance', to='ptw.permitworker')),
                ('tbt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='ptw.permittoolboxtalk')),
            ],
        ),
        migrations.AlterField(
            model_name='digitalsignature',
            name='signature_type',
            field=models.CharField(choices=[('requestor', 'Requestor'), ('verifier', 'Verifier'), ('issuer', 'Permit Issuer'), ('receiver', 'Permit Receiver'), ('approver', 'Approver'), ('safety_officer', 'Safety Officer'), ('area_manager', 'Area Manager'), ('witness', 'Witness')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='permittoolboxtalkattendance',
            unique_together={('tbt', 'permit_worker')},
        ),
    ]
