"""
Migration to add athens_tenant_id to authentication models
"""

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),  # Adjust based on your latest migration
    ]

    operations = [
        # Create AthensTenant table
        migrations.CreateModel(
            name='AthensTenant',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Athens Tenant ID', help_text='Unique tenant identifier generated by SAP')),
                ('company_id', models.UUIDField(blank=True, null=True, verbose_name='Company ID', help_text='Optional reference to legacy company identifier')),
                ('master_admin_id', models.UUIDField(verbose_name='Master Admin ID', help_text='Master admin user ID from SAP')),
                ('enabled_modules', models.JSONField(default=list, verbose_name='Enabled Modules', help_text='List of enabled modules for this tenant')),
                ('enabled_menus', models.JSONField(default=list, verbose_name='Enabled Menus', help_text='List of enabled menus for this tenant')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active', help_text='Whether this tenant is active and can access Athens')),
                ('tenant_name', models.CharField(blank=True, max_length=255, verbose_name='Tenant Name', help_text='Human-readable tenant name for identification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Athens Tenant',
                'verbose_name_plural': 'Athens Tenants',
                'db_table': 'athens_tenant',
            },
        ),
        
        # Create TenantAuditLog table
        migrations.CreateModel(
            name='TenantAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Tenant Created'), ('activated', 'Tenant Activated'), ('deactivated', 'Tenant Deactivated'), ('module_enabled', 'Module Enabled'), ('module_disabled', 'Module Disabled'), ('menu_enabled', 'Menu Enabled'), ('menu_disabled', 'Menu Disabled'), ('master_admin_changed', 'Master Admin Changed'), ('updated', 'Tenant Updated')], max_length=30, verbose_name='Action')),
                ('description', models.TextField(help_text='Detailed description of the action', verbose_name='Description')),
                ('previous_value', models.JSONField(blank=True, help_text='Previous value before change', null=True, verbose_name='Previous Value')),
                ('new_value', models.JSONField(blank=True, help_text='New value after change', null=True, verbose_name='New Value')),
                ('performed_by', models.UUIDField(blank=True, help_text='User ID who performed the action', null=True, verbose_name='Performed By')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='audit_logs', to='authentication.athenstenant')),
            ],
            options={
                'verbose_name': 'Tenant Audit Log',
                'verbose_name_plural': 'Tenant Audit Logs',
                'db_table': 'tenant_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        
        # Add athens_tenant_id to Project model
        migrations.AddField(
            model_name='project',
            name='athens_tenant_id',
            field=models.UUIDField(null=True, help_text='Athens tenant identifier for multi-tenant isolation'),
        ),
        
        # Add athens_tenant_id to CustomUser model
        migrations.AddField(
            model_name='customuser',
            name='athens_tenant_id',
            field=models.UUIDField(null=True, help_text='Athens tenant identifier for multi-tenant isolation'),
        ),
        
        # Add athens_tenant_id to UserDetail model
        migrations.AddField(
            model_name='userdetail',
            name='athens_tenant_id',
            field=models.UUIDField(null=True, help_text='Athens tenant identifier for multi-tenant isolation'),
        ),
        
        # Add athens_tenant_id to CompanyDetail model
        migrations.AddField(
            model_name='companydetail',
            name='athens_tenant_id',
            field=models.UUIDField(null=True, help_text='Athens tenant identifier for multi-tenant isolation'),
        ),
        
        # Add athens_tenant_id to AdminDetail model
        migrations.AddField(
            model_name='admindetail',
            name='athens_tenant_id',
            field=models.UUIDField(null=True, help_text='Athens tenant identifier for multi-tenant isolation'),
        ),
        
        # Add indexes for AthensTenant
        migrations.AddIndex(
            model_name='athenstenant',
            index=models.Index(fields=['master_admin_id'], name='auth_athenstenant_master_admin_idx'),
        ),
        migrations.AddIndex(
            model_name='athenstenant',
            index=models.Index(fields=['is_active'], name='auth_athenstenant_is_active_idx'),
        ),
        
        # Add indexes for TenantAuditLog
        migrations.AddIndex(
            model_name='tenantauditlog',
            index=models.Index(fields=['tenant', '-timestamp'], name='tenant_audit_tenant_time_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantauditlog',
            index=models.Index(fields=['action'], name='tenant_audit_action_idx'),
        ),
        
        # Add indexes for athens_tenant_id fields
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['athens_tenant_id'], name='auth_project_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['athens_tenant_id'], name='auth_customuser_tenant_idx'),
        ),
    ]