# Generated by Django 5.2.9 on 2026-01-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_athens_tenant_id'),
        ('authentication', '0007_alter_customuser_user_type'),
    ]

    operations = [
    ]
