# Generated by Django 5.2.9 on 2026-01-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_merge_20260103_1152'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='auth_customuser_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='project',
            name='auth_project_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='athenstenant',
            new_name='athens_tena_master__2288f8_idx',
            old_name='auth_athenstenant_master_admin_idx',
        ),
        migrations.RenameIndex(
            model_name='athenstenant',
            new_name='athens_tena_is_acti_19ab61_idx',
            old_name='auth_athenstenant_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantauditlog',
            new_name='tenant_audi_tenant__f28a40_idx',
            old_name='tenant_audit_tenant_time_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantauditlog',
            new_name='tenant_audi_action_7cadd7_idx',
            old_name='tenant_audit_action_idx',
        ),
        migrations.AddField(
            model_name='project',
            name='client_company_id',
            field=models.UUIDField(blank=True, help_text='Client company athens_tenant_id', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contractor_company_ids',
            field=models.JSONField(default=list, help_text='List of contractor company athens_tenant_ids'),
        ),
        migrations.AddField(
            model_name='project',
            name='epc_company_id',
            field=models.UUIDField(blank=True, help_text='EPC company athens_tenant_id', null=True),
        ),
        migrations.AlterField(
            model_name='admindetail',
            name='athens_tenant_id',
            field=models.UUIDField(blank=True, help_text='Athens tenant identifier for multi-tenant isolation', null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='athens_tenant_id',
            field=models.UUIDField(blank=True, help_text='Athens tenant identifier for multi-tenant isolation', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='athens_tenant_id',
            field=models.UUIDField(blank=True, help_text='Company that owns this business project', null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='athens_tenant_id',
            field=models.UUIDField(blank=True, help_text='Athens tenant identifier for multi-tenant isolation', null=True),
        ),
    ]
