# Generated by Django 5.1.4 on 2026-01-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_create_menu_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodule',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('master', 'Master'), ('projectadmin', 'Project Admin'), ('adminuser', 'Admin User')], max_length=20),
        ),
    ]
