# Generated by Django 5.1.4 on 2026-01-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_add_password_reset_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('master', 'Master'), ('projectadmin', 'Project Admin'), ('user', 'User'), ('adminuser', 'Admin User')], max_length=20),
        ),
    ]
