#!/bin/bash
# Quick setup script

echo "E2E Test Framework Setup"
echo "========================"
echo ""
echo "✓ Framework files created"
echo "✓ Selectors fixed (Athens uses #id, SAP uses name)"
echo ""
echo "Next steps:"
echo "1. Edit .env.e2e with real test credentials:"
echo "   nano .env.e2e"
echo ""
echo "2. Run authentication:"
echo "   npm run auth:athens"
echo "   npm run auth:sap"
echo ""
echo "3. Run tests:"
echo "   npm run test:all"
echo ""
echo "Troubleshooting:"
echo "- View screenshots: ls test-results/"
echo "- Inspect login forms: node inspect-login.js"
echo "- View trace: npx playwright show-trace test-results/*/trace.zip"
