# Generated by Django 5.2.9 on 2026-01-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0003_merge_0002_add_athens_tenant_id_0002_mom_project'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='mom',
            name='mom_mom_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='mom',
            name='mom_mom_tenant_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='participantattendance',
            name='mom_attendance_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='participantresponse',
            name='mom_response_tenant_idx',
        ),
        migrations.RemoveField(
            model_name='mom',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='participantattendance',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='participantresponse',
            name='athens_tenant_id',
        ),
    ]
