# Generated by Django 5.2.5 on 2025-08-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental'), ('differential', 'Differential')], default='full', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='backups/')),
                ('size', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(default='EHS Management System', max_length=200)),
                ('siteDescription', models.TextField(blank=True, default='')),
                ('maintenanceMode', models.BooleanField(default=False)),
                ('allowRegistration', models.BooleanField(default=False)),
                ('defaultUserRole', models.CharField(default='clientuser', max_length=50)),
                ('sessionTimeout', models.PositiveIntegerField(default=60)),
                ('maxFileSize', models.PositiveIntegerField(default=10)),
                ('emailNotifications', models.BooleanField(default=True)),
                ('smsNotifications', models.BooleanField(default=False)),
                ('backupFrequency', models.CharField(default='daily', max_length=50)),
                ('logLevel', models.CharField(default='INFO', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
