# Generated by Django 5.2.9 on 2026-01-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_add_athens_tenant_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='environmentalincident',
            name='env_incident_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='environmentaspect',
            name='env_aspect_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='generationdata',
            name='env_generation_tenant_idx',
        ),
        migrations.RemoveIndex(
            model_name='wastemanifest',
            name='env_waste_tenant_idx',
        ),
        migrations.RemoveField(
            model_name='biodiversityevent',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='carbonfootprint',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='emissionfactor',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='energymanagement',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='environmentalincident',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='environmentalmonitoring',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='environmentaspect',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='esgpolicy',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='generationdata',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='ghgactivity',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='sustainabilitytarget',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='wastemanifest',
            name='athens_tenant_id',
        ),
        migrations.RemoveField(
            model_name='watermanagement',
            name='athens_tenant_id',
        ),
    ]
