# Generated by Django 5.2.9 on 2026-01-08 07:47

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperadminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('superadmin', 'Superadmin'), ('support', 'Support')], default='superadmin', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collaboration_projects', to='control_plane.superadminuser')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('target_type', models.CharField(blank=True, max_length=255)),
                ('target_id', models.CharField(blank=True, max_length=255)),
                ('request_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaboration_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_plane.collaborationproject')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control_plane.tenantcompany')),
            ],
        ),
        migrations.CreateModel(
            name='TenantDatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_key', models.CharField(max_length=255, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='db_config', to='control_plane.tenantcompany')),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationSharePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('allowed_actions', models.JSONField(default=list)),
                ('filters', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaboration_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_policies', to='control_plane.collaborationproject')),
            ],
            options={
                'unique_together': {('collaboration_project', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_project_id', models.CharField(max_length=64)),
                ('mapping_type', models.CharField(choices=[('canonical', 'Canonical'), ('mirrored', 'Mirrored'), ('external', 'External')], default='canonical', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaboration_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='control_plane.collaborationproject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='control_plane.tenantcompany')),
            ],
            options={
                'unique_together': {('collaboration_project', 'tenant', 'tenant_project_id')},
            },
        ),
        migrations.CreateModel(
            name='CollaborationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Client'), ('epc', 'EPC'), ('contractor', 'Contractor'), ('viewer', 'Viewer')], max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaboration_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='control_plane.collaborationproject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_memberships', to='control_plane.tenantcompany')),
            ],
            options={
                'unique_together': {('collaboration_project', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='control_plane.tenantcompany')),
            ],
            options={
                'unique_together': {('tenant', 'email')},
            },
        ),
        migrations.CreateModel(
            name='TenantModuleSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('plan_tier', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_subscriptions', to='control_plane.tenantcompany')),
            ],
            options={
                'unique_together': {('tenant', 'module_code')},
            },
        ),
    ]
