# Generated by Django 5.2.9 on 2026-01-08 08:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_plane', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantcompany',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
